version: '3.8'

services:
  server:
    build:
      context: .
    container_name: restaurant
    ports:
      - '${PORT}:${PORT}'  # استفاده از متغیر PORT از فایل .env
    environment:
      - PORT=${PORT}
      - PG_HOST=${PG_HOST}
      - PG_PORT=${PG_PORT}
      - PG_DATABASE=${PG_DATABASE}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
    volumes: 
      - .:/app
      - /app/node_modules
    networks:
      - saleh-network

networks:
  saleh-network:
    external: true
