version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres
    ports:
      - '5432:5432'  # استفاده از پورت پیش‌فرض PostgreSQL
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - saleh-network

volumes:
  pg_data:

networks:
  saleh-network:
    external: true

